# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f138aaddbea173413b312f0cb789edbd1ad732629507ebdf1b50e40a62ce442a3132ab5ef61e5c65523bc7f6c0f7d72a8a2da5569fb5f78475ba1d9e10f7b3ee

test:
  secret_key_base: 3f415103326b242c7670dd0e6a5df5e6298ad3b1ab1702d035c88edac4750fa23b92bcd4374227bd0968adc06de0bc6afacc42e265a2d9c18a75d484a83ea772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
